only_rules:
  - closure_spacing
  - colon
  - empty_enum_arguments
  - fatal_error_message
  - force_try
  #- force_unwrapping
  #- implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules
  - line_length
  #- force_cast

line_length:
  warning: 160
  error: 400
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

included:
  - Woowbe

excluded:
  - Carthage
  - Pods

colon:
  apply_to_dictionaries: false

indentation: 4

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
